### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by jmrunge** [inaes-tic/mbc-mosto#16]
We should write some tests for Mosto and its drivers to be sure nothing is not being taking care of.  They should be implemented using Mocha.  For examples look at https://github.com/inaes-tic/melted-node/blob/master/mocha.js

**Comment by jmrunge** [comment]
Added pull request #21 with basic test for example.

**Comment by jmrunge** [comment]
@csrocha Could you explain how to use your Makefile for testing? Tried "make test" and throwed error.

**Comment by csrocha** [comment]
@jmrunge What errors do you get? I tried it and did have some errors on the absolute file paths, your absolute paths! But that'll solve it soon. Can you show me the output after "make test"?

**Comment by csrocha** [comment]
@jmrunge I'm changing test code. First absolute paths, but now the logic. But I need your help.

You have a really big one test. I prefer shorts and simple: One for connection only; Other for connect and check status; Other for connect and play a playlist; Could you prepare these? Now I will send a pull request with simple but useful changes. If you break your test in short unit-test and append new comments describing what thay do and what you expect - nothing complicated - will be really useful.

**Comment by csrocha** [comment]
@jmrunge I just understand your test organization. They have hierarchical structure. That's ok.

Now, to get all paths relative to mbc-mosto root, I had create a .png file to use in a playlist (.mtl). And I append a line in Makefile to create .avi and .mp4 from this png. Then will be a .png, .avi, .mp4, .mtl files available for testing in test/images, test/videos, and test/playlists directories.

I changed test/mvcp-driver-test.js but it not easy. I got the following error:

'''
$ make
npm install
/usr/local/bin/melted
/usr/bin/nodejs node_modules/mocha/bin/mocha
mbc-mosto: [INFO] Creating server for type [melted]
mbc-mosto: [INFO] Creating server instance [localhost:5250]
mbc-mosto: [INFO] Server instance created [localhost:5250]

  mbc-mosto: [INFO] Connecting to server instance [localhost:5250]
melted-node: [connect] Invoked
melted-node: [connect] Connected to Melted Server
melted-node: [expect] Invoked to expect: 100 VTR Ready
melted-node: [expect] Received: 100 VTR Ready

melted-node: [expect] Formatted Response: 100 VTR Ready
melted-node: [expect] Received expected response
melted-node: [expect] Invoked to expect: 100 VTR Ready
melted-node: [expect] Received: 402 Argument missing
melted-node: [expect] Formatted Response: 402 Argument missing
melted-node: [processQueue] Invoked
melted-node: [processQueue] Nothing else to process
․mbc-mosto: [INFO] Sending command: STOP U0
melted-node: [sendCommand] Invoked for command: STOP U0, expected: 200 OK
melted-node: [addCommandToQueue] Invoked for command: STOP U0, expected: 200 OK
melted-node: [processQueue] Invoked
melted-node: [processQueue] Processing command: STOP U0
melted-node: [_sendCommand] Sending command: STOP U0
melted-node: [expect] Invoked to expect: 200 OK
melted-node: [expect] Received: 

melted-node: [expect] Formatted Response: 
melted-node: [expect] Received empty string, retrying
melted-node: [expect] Invoked to expect: 200 OK
melted-node: [expect] Received: 403 Unit not found

melted-node: [expect] Formatted Response: 403 Unit not found
melted-node: [expect] Expected '200 OK' but got '403 Unit not found' !
melted-node: [expect] Invoked to expect: 200 OK
melted-node: [expect] Received: 402 Argument missing
melted-node: [expect] Formatted Response: 402 Argument missing
[Error: melted-node: [processQueue] Error processing command: STOP U0 [403 Unit not found
]]
melted-node: [processQueue] Invoked
melted-node: [processQueue] Nothing else to process
melted-node: [processQueue] Calling error callback: 
403 Unit not found

․

  ✖ 1 of 94 tests failed:

  1) commands #load "before all" hook:
     Error: timeout of 2000ms exceeded
      at Object.<anonymous> (/home/crocha/Proyectos/tda/mbc-mosto/node_modules/mocha/lib/runnable.js:167:14)
      at Timer.ontimeout (timers.js:94:19)
'''

That error happens when you not setup a new unit. You must do it by hand! We need add in the test unit the U0 creation or in source, if not exists U0 create one. If you made it be hand and execute again the test you get:

'''
$ melted
$ telnet localhost 5250
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
100 VTR Ready
NLS
201 OK

UADD sdl
201 OK
U0

ULS
201 OK
U0 00 sdl 1

Connection closed by foreign host.
$ make test
npm install
/usr/local/bin/melted
bind: La dirección ya se está usando
/usr/bin/nodejs node_modules/mocha/bin/mocha
mbc-mosto: [INFO] Creating server for type [melted]
mbc-mosto: [INFO] Creating server instance [localhost:5250]
mbc-mosto: [INFO] Server instance created [localhost:5250]

  mbc-mosto: [INFO] Connecting to server instance [localhost:5250]
melted-node: [connect] Invoked
melted-node: [connect] Connected to Melted Server
melted-node: [expect] Invoked to expect: 100 VTR Ready
melted-node: [expect] Received: 100 VTR Ready

melted-node: [expect] Formatted Response: 100 VTR Ready
melted-node: [expect] Received expected response
melted-node: [expect] Invoked to expect: 100 VTR Ready
melted-node: [expect] Received: 402 Argument missing
melted-node: [expect] Formatted Response: 402 Argument missing
melted-node: [processQueue] Invoked
melted-node: [processQueue] Nothing else to process
․mbc-mosto: [INFO] Sending command: STOP U0
melted-node: [sendCommand] Invoked for command: STOP U0, expected: 200 OK
melted-node: [addCommandToQueue] Invoked for command: STOP U0, expected: 200 OK
melted-node: [processQueue] Invoked
melted-node: [processQueue] Processing command: STOP U0
melted-node: [_sendCommand] Sending command: STOP U0
melted-node: [expect] Invoked to expect: 200 OK
melted-node: [expect] Received: 

melted-node: [expect] Formatted Response: 
melted-node: [expect] Received empty string, retrying
melted-node: [expect] Invoked to expect: 200 OK
melted-node: [expect] Received: 200 OK

melted-node: [expect] Formatted Response: 200 OK
melted-node: [expect] Received expected response
melted-node: [expect] Invoked to expect: 200 OK
melted-node: [expect] Received: 402 Argument missing
melted-node: [expect] Formatted Response: 402 Argument missing
melted-node: [processQueue] Calling success callback: 
mbc-mosto: [INFO] Sending command: CLEAR U0
melted-node: [sendCommand] Invoked for command: CLEAR U0, expected: 200 OK
melted-node: [addCommandToQueue] Invoked for command: CLEAR U0, expected: 200 OK
melted-node: [processQueue] Invoked
melted-node: [processQueue] Processing command: CLEAR U0
melted-node: [_sendCommand] Sending command: CLEAR U0
melted-node: [expect] Invoked to expect: 200 OK
melted-node: [expect] Received: 

melted-node: [expect] Formatted Response: 
melted-node: [expect] Received empty string, retrying
melted-node: [expect] Invoked to expect: 200 OK
melted-node: [expect] Received: 200 OK

melted-node: [expect] Formatted Response: 200 OK
melted-node: [expect] Received expected response
melted-node: [expect] Invoked to expect: 200 OK
melted-node: [expect] Received: 402 Argument missing
melted-node: [expect] Formatted Response: 402 Argument missing
melted-node: [processQueue] Calling success callback: 
mbc-mosto: [INFO] Generating file videos/SMPTE_Color_Bars.mp4
mbc-mosto: [INFO] Creating playlist xml object for file videos/SMPTE_Color_Bars.mp4
mbc-mosto: [INFO] Creating track xml object for file videos/SMPTE_Color_Bars.mp4
mbc-mosto: [INFO] Creating multitrack xml object for file videos/SMPTE_Color_Bars.mp4
mbc-mosto: [INFO] Creating tractor xml object for file videos/SMPTE_Color_Bars.mp4
mbc-mosto: [INFO] Pushing xml for file videos/SMPTE_Color_Bars.mp4
mbc-mosto: [INFO] Writing file ./test/playlists/SMPTE_Color_Bars.mp4.xml
melted-node: [processQueue] Invoked
melted-node: [processQueue] Nothing else to process
mbc-mosto: [INFO] File ready: ./test/playlists/SMPTE_Color_Bars.mp4.xml
mbc-mosto: [INFO] Sending command: LOAD U0 ./test/playlists/SMPTE_Color_Bars.mp4.xml
melted-node: [sendCommand] Invoked for command: LOAD U0 ./test/playlists/SMPTE_Color_Bars.mp4.xml, expected: 200 OK
melted-node: [addCommandToQueue] Invoked for command: LOAD U0 ./test/playlists/SMPTE_Color_Bars.mp4.xml, expected: 200 OK
melted-node: [processQueue] Invoked
melted-node: [processQueue] Processing command: LOAD U0 ./test/playlists/SMPTE_Color_Bars.mp4.xml
melted-node: [_sendCommand] Sending command: LOAD U0 ./test/playlists/SMPTE_Color_Bars.mp4.xml
melted-node: [expect] Invoked to expect: 200 OK
melted-node: [expect] Received: 

melted-node: [expect] Formatted Response: 
melted-node: [expect] Received empty string, retrying
melted-node: [expect] Invoked to expect: 200 OK
melted-node: [expect] Received: 404 Failed to locate or open clip

melted-node: [expect] Formatted Response: 404 Failed to locate or open clip
melted-node: [expect] Expected '200 OK' but got '404 Failed to locate or open clip' !
melted-node: [expect] Invoked to expect: 200 OK
melted-node: [expect] Received: 402 Argument missing
melted-node: [expect] Formatted Response: 402 Argument missing
[Error: melted-node: [processQueue] Error processing command: LOAD U0 ./test/playlists/SMPTE_Color_Bars.mp4.xml [404 Failed to locate or open clip
]]
melted-node: [processQueue] Invoked
melted-node: [processQueue] Nothing else to process
melted-node: [processQueue] Calling error callback: 
404 Failed to locate or open clip

․

  ✖ 1 of 94 tests failed:

  1) commands #load "before all" hook:
     Error: timeout of 2000ms exceeded
      at Object.<anonymous> (/home/crocha/Proyectos/tda/mbc-mosto/node_modules/mocha/lib/runnable.js:167:14)
      at Timer.ontimeout (timers.js:94:19)

make: [test] Error 1 (no tiene efecto)
killall melted
'''

This other error show that we need setup the playlist root to melted (http://www.mltframework.org/bin/view/MLT/Testing - Section 3.3).

Then, our issues to make testing work using relative paths are:

1) Create Units when are necessary.

2) Set the root to melted.

**Comment by jmrunge** [comment]
Yes, indeed we need to setup the root to melted if we will be using
relative paths.  I've thought that melted init should be ouside mosto, but
we can have it inside it.  What about an init script that mosto could run?
This script should do only one thing: Start melted.  And it should be
runned from the error handler in mosto that handles mvcp connection error.
It can be a single command line in mosto config too.  Then, set up root.
After, we should ask for ULS.  If U0 is not present, we should create it.
What type of unit should be in config too (sdl, decklink, bluefish,
avformat, etc).  I can implement ULS in mvcp driver.  And shutdown too.
This way, in tests we could:
- Shutdown melted
- Start it
- Set root
- Add unit
- Start all tests

What do you think about it?

PS: Here is the output of "make test"

jmrunge@wks-it3-brc:~/mbc/mbc-mosto$ make test
npm install
/usr/local/bin/node /usr/bin/nodejs node_modules/mocha/bin/mocha

/usr/bin/nodejs:1
ELF
^

module.js:434
  var compiledWrapper = runInThisContext(wrapper, filename, true);
                        ^
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:434:25)
    at Object..js (module.js:464:10)
    at Module.load (module.js:353:32)
    at Function._load (module.js:311:12)
    at Array.0 (module.js:484:10)
    at EventEmitter._tickCallback (node.js:190:39)
make: **\* [test] Error 1

2013/4/6 Cristian Sebastian Rocha notifications@github.com

**Comment by csrocha** [comment]
@jmrunge : You can see the troubles about your last comment in #39 . I will close this issue and create new one.

**Comment by csrocha** [comment]
The new issue is #55 .
