### ISSUE TITLE
Clip to play when nothing is scheduled

### ISSUE THREAD

**Issue by jmrunge** [inaes-tic/mbc-mosto#19]
To prevent black screen to air, we need to setup on mosto config a clip (or image) to be played when nothing is scheduled to show on air.

**Comment by jmrunge** [comment]
I think this was done in #74 .  @fabriciocosta can you confirm?  And, please change the black image to something different (mbc-playout logo image?) so we can know when black image is playing and when we get a black screen (if this fails).

**Comment by fabriciocosta** [comment]
Well, i named it "black" in config.json. And based and what i understand about mlt it takes whatever you put there (.mp4, .mov, etc) . By default it's named "../../images/black.png" , the "../../" it's because we are using "./test/playlist" as base directory for xml files. I didn't tested it with a video media, but it should work. Maybe it's better to have a black/static screen, and a video/loop version... It has to be defined somewhere in mbc-common and i think it's already placed in the general configuration (check mbc-common).

**Comment by xaiki** [comment]
config should be more descriptive than 'black'
if not it's going to be impossible to define from caspa.

@jmrunge, you should give fabricio a model (i.e. a {}) of what is needed
(strictly) to be able to generate inteligently.

we don't need black.png, there is a color consumer.

On 23 April 2013 12:58, Fabricio Costa Alisedo notifications@github.comwrote:

> Well, i named it "black" in config.json. And based and what i understand
> about mlt it takes whatever you put there (.mp4, .mov, etc) . By default
> it's named "../../images/black.png" , the "../../" it's because we are
> using "./test/playlist" as base directory for xml files. I didn't tested it
> with a video media, but it should work. Maybe it's better to have a
> black/static screen, and a video/loop version... It has to be defined
> somewhere in mbc-common and i think it's already placed in the general
> configuration (check mbc-common).
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/inaes-tic/mbc-mosto/issues/19#issuecomment-16867496
> .

## 

Niv Sardi

**Comment by jmrunge** [comment]
What I had in mind is that every TV station could configure what to show. I had thought by default (in config) a png with mbc playout logo. Not sure what do you mean with a model or more inteligently. Can you explain your idea?

-----Original Message-----

**Comment by xaiki** [comment]
Something node-mlt could grok.
We need more than PNG.

Color,
PNG
Pngs
Video
....
