### ISSUE TITLE
Move default snap or fixed attr of playlists to config

### ISSUE THREAD

**Issue by jmrunge** [inaes-tic/mbc-mosto#71]
Please move out from mongo driver to playlists driver config file the hardcoded value "snap" when creating a playlist.  Also, Caspa does handle this?

**Comment by xaiki** [comment]
>  Please move out from mongo driver to playlists driver config file the
>  hardcoded value "snap" when creating a playlist. Also, Caspa does handle
>  this?

caspa handles this, and you should use the exact same code.
this has been discussed.

**Comment by jmrunge** [comment]
Ok, @Lacrymology could take a look at this?

**Comment by xaiki** [comment]
@jmrunge please kill your quoting on blackberry, it look ugly both in emails and github.

this is for @fabriciocosta as it's his code.

**Comment by xaiki** [comment]
hum, it should be in mosto.js, this behaviour is duplicated in json and mongo driver.

**Comment by Lacrymology** [comment]
I don't know about that. JSON and mongo drivers handle different formats, so the way they read the "snap" or "fixed" is driver-dependant.

Right now, nobody handles this, this is why there's a hardcoded default in the drivers. I don't know exactly what's the best way to handle this until we know what's the desired interface for generating "fixed" playlists. AFAICS, it should be an interface different than the scheduler, because you'd be working precisely at **overriding** scheduled playlists.

OTOH, I don't see why the default should be configurable, why should the default be "fixed", when we **know** we have 1m accuracy on the calendar, and we'll need ms accuracy for this?

based on what I can imagine, I think scheduler should send playlists with nothing (or a hardcoded "snap"), and this "override" (or direct control) interface should have the option to send "snap" or "fixed".

by the way, I'm guessing "snap" means "fix timing discrepancies of under X frames" and "fixed" means "don't do that"

**Comment by xaiki** [comment]
On 21 April 2013 02:09, Tomas Neme notifications@github.com wrote:

> I don't know about that. JSON and mongo drivers handle different formats,
> so the way they read the "snap" or "fixed" is driver-dependant.

different input formats,... snap or fixed are clearly output formats, that
by a driver's definition, should be identical.

> Right now, nobody handles this, this is why there's a hardcoded default in
> the drivers. I don't know exactly what's the best way to handle this until
> we know what's the desired interface for generating "fixed" playlists.
> AFAICS, it should be an interface different than the scheduler, because
> you'd be working precisely at _overriding_ scheduled playlists.

making it a config value is costless, and effortless, doesn't change
anything in the current code nor state of affairs.

> OTOH, I don't see why the default should be configurable,

because it comes at 0 cost...

> why should the default be "fixed",
> 
> when we _know_ we have 1m accuracy on the calendar, and we'll need ms
> accuracy for this?

no we don't, we have 1m scheduling acurracy, but with snaping we have
frame-perfect snapping accuracy in caspa.
we can't allow a time drift between mosto and caspa.

> based on what I can imagine, I think scheduler should send playlists with
> nothing (or a hardcoded "snap"), and this "override" (or direct control)
> interface should have the option to send "snap" or "fixed".

overrides still go through caspa, there's no need for special handeling.

> by the way, I'm guessing "snap" means "fix timing discrepancies of under X
> frames" and "fixed" means "don't do that"

 snap means: snap to upper end-of-feed, i.e. don't allow unscheduled frames.

## 

Niv Sardi

**Comment by Lacrymology** [comment]
For some reason your email client breaks github formatting..

> > I don't know about that. JSON and mongo drivers handle different formats,
> > so the way they read the "snap" or "fixed" is driver-dependant.
> > different input formats,... snap or fixed are clearly output formats, that
> 
> by a driver's definition, should be identical.

Then you're saying.. what? that mosto should assume that if no value is present, then it must be the default?

No, this should actually go to the `api.Playlist` module. `this.mode = mode || config.playlist_default_mode` or something

> > Right now, nobody handles this, this is why there's a hardcoded default in
> > the drivers. I don't know exactly what's the best way to handle this until
> > we know what's the desired interface for generating "fixed" playlists.
> > AFAICS, it should be an interface different than the scheduler, because
> > you'd be working precisely at _overriding_ scheduled playlists.
> 
> making it a config value is costless, and effortless, doesn't change
> 
> anything in the current code nor state of affairs.
> 
> > OTOH, I don't see why the default should be configurable,
> 
> because it comes at 0 cost...

yes, you're confusing my answers. If we change the code from `..., "fixed")` to `..., config.playlist_default_mode)` it will not be any less "hardcoded" as far as the driver is concerned. We agree that making it a config value is free and it's OK, the other part (that caspa has no way to handle this) has not been addressed.

> > when we _know_ we have 1m accuracy on the calendar, and we'll need ms
> > accuracy for this?
> 
> no we don't, we have 1m scheduling acurracy, but with snaping we have
> frame-perfect snapping accuracy in caspa.
> we can't allow a time drift between mosto and caspa.

no we don't. We have a 1s accuracy in caspa, because occurrence start and end are linux timestamps, which are in seconds.

> > based on what I can imagine, I think scheduler should send playlists with
> > nothing (or a hardcoded "snap"), and this "override" (or direct control)
> > interface should have the option to send "snap" or "fixed".
> 
> overrides still go through caspa, there's no need for special handeling.

wat? yes, right, there's no need for special handling on the mosto side.. but caspa will need a specific interface for this. This interface doesn't exist yet. What are you arguing about?

> > by the way, I'm guessing "snap" means "fix timing discrepancies of under X
> > frames" and "fixed" means "don't do that"
> 
> snap means: snap to upper end-of-feed, i.e. don't allow unscheduled frames.

no, it's not what it means. At least it's not what the semantics in the code are. @fabriciocosta can probably say better, though

**Comment by Lacrymology** [comment]
This is not in mosto anymore. Caspa is supposed to handle this, and mosto just picks up whatever schedules reach the database
